services:
  db:
    image: postgres:15
    env_file:
      - .env
    networks:
      - wb_net

  app:
    build: 
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8888:8888"
    depends_on:
      - db
    networks:
      - wb_net
    volumes:
      - ./src/api:/app

networks:
  wb_net:
    driver: bridge
