services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow 
    networks:
      - wb_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow 
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wb_net
    volumes:
      - ./src/api:/app

  bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - .bot.env
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow 
    ports:
      - "8889:8889"
    networks:
      - wb_net
    volumes:
      - ./src/bot:/app
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  wb_net:
    driver: bridge
